#!/bin/bash
source /opt/ros/melodic/setup.bash
clear
cat << "EOF"
  _      _   ___ _  _ ___ ___ _
 | |    /_\ / __| || |_ _| __/_\
 | |__ / _ \\__ \ __ || || _/ _ \
 |____/_/ \_\___/_||_|___|_/_/ \_\
EOF
roscore &
pushd ~/code/ServiceRobotControlStack
source devel/setup.bash
sleep 1.5
rosbuild_ws/robot_status_gui/robot_status_gui/bin/gui_monitor --config=rosbuild_ws/robot_status_gui/gui_config/gui_config.txt --runall
killall rviz
killall roscore
sleep 1
popd